# tested instructions
instruction_categories:
  - BASE-NOP
  - BASE-BINARY
  - BASE-BITBYTE
  - BASE-CMOV
  - BASE-CONVERT
  - BASE-DATAXFER
  - BASE-FLAGOP
  - BASE-SETCC
  - BASE-LOGICAL
  - BASE-POP
  - BASE-PUSH

# contract
x86_executor_enable_ssbp_patch: false

contract_observation_clause: ct
contract_execution_clause:
  - seq


# enable perf. optimizations
enable_speculation_filter: true
enable_observation_filter: true
enable_fast_path_model: true